const countryList = {
  ADA: "ADA", // Cardano (cryptocurrency)
  AED: "AE",
  AFN: "AF",
  ALL: "AL",
  AMD: "AM",
  ANG: "AN", // Netherlands Antilles
  AOA: "AO",
  ARB: "ARB", // Arbitrum (cryptocurrency)
  ARS: "AR",
  AUD: "AU",
  AVAX: "AVAX", // Avalanche (cryptocurrency)
  AWG: "AW",
  AZN: "AZ",
  BAM: "BA",
  BBD: "BB",
  BDT: "BD",
  BGN: "BG",
  BHD: "BH",
  BIF: "BI",
  BMD: "BM",
  BNB: "BNB", // Binance Coin (cryptocurrency)
  BND: "BN",
  BOB: "BO",
  BRL: "BR",
  BSD: "BS",
  BTC: "BTC", // Bitcoin (cryptocurrency)
  BTN: "BT",
  BWP: "BW",
  BYN: "BY",
  BYR: "BY", // Old Belarusian Ruble
  BZD: "BZ",
  CAD: "CA",
  CDF: "CD",
  CHF: "CH",
  CLF: "CL", // Unidad de Fomento (funds code)
  CLP: "CL",
  CNY: "CN",
  COP: "CO",
  CRC: "CR",
  CUC: "CU",
  CUP: "CU",
  CVE: "CV",
  CZK: "CZ",
  DAI: "DAI", // Dai (cryptocurrency)
  DJF: "DJ",
  DKK: "DK",
  DOP: "DO",
  DOT: "DOT", // Polkadot (cryptocurrency)
  DZD: "DZ",
  EGP: "EG",
  ERN: "ER",
  ETB: "ET",
  ETH: "ETH", // Ethereum (cryptocurrency)
  EUR: "EU",
  FJD: "FJ",
  FKP: "FK",
  GBP: "GB",
  GEL: "GE",
  GGP: "GG",
  GHS: "GH",
  GIP: "GI",
  GMD: "GM",
  GNF: "GN",
  GTQ: "GT",
  GYD: "GY",
  HKD: "HK",
  HNL: "HN",
  HRK: "HR",
  HTG: "HT",
  HUF: "HU",
  IDR: "ID",
  ILS: "IL",
  IMP: "IM",
  INR: "IN",
  IQD: "IQ",
  IRR: "IR",
  ISK: "IS",
  JEP: "JE",
  JMD: "JM",
  JOD: "JO",
  JPY: "JP",
  KES: "KE",
  KGS: "KG",
  KHR: "KH",
  KMF: "KM",
  KPW: "KP",
  KRW: "KR",
  KWD: "KW",
  KYD: "KY",
  KZT: "KZ",
  LAK: "LA",
  LBP: "LB",
  LKR: "LK",
  LRD: "LR",
  LSL: "LS",
  LTC: "LTC", // Litecoin (cryptocurrency)
  LTL: "LT", // Lithuanian Litas (historical)
  LVL: "LV", // Latvian Lats (historical)
  LYD: "LY",
  MAD: "MA",
  MATIC: "MATIC", // Polygon (cryptocurrency)
  MDL: "MD",
  MGA: "MG",
  MKD: "MK",
  MMK: "MM",
  MNT: "MN",
  MOP: "MO",
  MRO: "MR", // Old Mauritanian Ouguiya
  MRU: "MR",
  MUR: "MU",
  MVR: "MV",
  MWK: "MW",
  MXN: "MX",
  MYR: "MY",
  MZN: "MZ",
  NAD: "NA",
  NGN: "NG",
  NIO: "NI",
  NOK: "NO",
  NPR: "NP",
  NZD: "NZ",
  OMR: "OM",
  OP: "OP", // Optimism (cryptocurrency)
  PAB: "PA",
  PEN: "PE",
  PGK: "PG",
  PHP: "PH",
  PKR: "PK",
  PLN: "PL",
  PYG: "PY",
  QAR: "QA",
  RON: "RO",
  RSD: "RS",
  RUB: "RU",
  RWF: "RW",
  SAR: "SA",
  SBD: "SB",
  SCR: "SC",
  SDG: "SD",
  SEK: "SE",
  SGD: "SG",
  SHP: "SH",
  SLL: "SL",
  SOL: "SOL", // Solana (cryptocurrency)
  SOS: "SO",
  SRD: "SR",
  STD: "ST", // Old São Tomé and Príncipe Dobra
  STN: "ST",
  SVC: "SV",
  SYP: "SY",
  SZL: "SZ",
  THB: "TH",
  TJS: "TJ",
  TMT: "TM",
  TND: "TN",
  TOP: "TO",
  TRY: "TR",
  TTD: "TT",
  TWD: "TW",
  TZS: "TZ",
  UAH: "UA",
  UGX: "UG",
  USD: "US",
  USDC: "USDC", // USD Coin (cryptocurrency)
  USDT: "USDT", // Tether (cryptocurrency)
  UYU: "UY",
  UZS: "UZ",
  VEF: "VE", // Old Venezuelan Bolívar
  VES: "VE",
  VND: "VN",
  VUV: "VU",
  WST: "WS",
  XAF: "CF",
  XAG: "XAG", // Silver (commodity)
  XAU: "XAU", // Gold (commodity)
  XCD: "AG",
  XDR: "XDR", // Special Drawing Rights
  XOF: "BJ",
  XPD: "XPD", // Palladium (commodity)
  XPF: "PF",
  XPT: "XPT", // Platinum (commodity)
  XRP: "XRP", // Ripple (cryptocurrency)
  YER: "YE",
  ZAR: "ZA",
  ZMK: "ZM", // Old Zambian Kwacha
  ZMW: "ZM",
  ZWL: "ZW",
};